### ISSUE TITLE
Замечания по lw2

### ISSUE THREAD

**Issue by ivklgn** [borsh357/lw2-forms#1]
**Task2**

```css
textarea:focus, input:focus {
  outline: none;
  background: rgba(215, 232, 247, 0.4);
  
}

textarea, input {
  border: #787e9c 2px solid;
  border-radius: 5px;
  font-size: 0.8em;
  width: 100%;
}
```

лучше не стилизовать элементы, используйте классы
